server:
  port: 9003
spring :
  application :
    name : questions-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    hostname : localhost
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/